import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import { api } from "@/utils/api";
import { useRouter } from "next/router";
import { useState } from "react";
import { ArrowBigRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PlanningForm } from "@/components/PlanningForm";
import { toast } from "react-toastify";

export default function Home() {
  const { data } = useSession();
  const router = useRouter();
  const [planning, setPlanning] = useState("");

  const { mutateAsync } = api.room.create.useMutation({
    onSuccess(data, variables, context) {
      router.push(`/room/${data.id}`);
    },
  });

  const handleCreateRoom = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const input = event.currentTarget.elements.namedItem(
      "planning-form",
    ) as HTMLInputElement | null;
    if (!input?.value || !input.value) {
      toast.error("Digite o nome da sala");
    }
    const value = input.value;
    try {
      await mutateAsync({ planning: value });
    } catch (e) {
      console.log(e);
    }
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full flex-col items-center  justify-center bg-gradient-to-b  ">
        {!data && (
          <Button
            onClick={() => signIn("discord")}
            className="w-60"
            variant="default"
          >
            Login
          </Button>
        )}

        {data && (
          <PlanningForm onSubmit={handleCreateRoom}>
            <Button className="w-60" variant="default">
              Create room
              <ArrowBigRight size={25} />
            </Button>
          </PlanningForm>
        )}
      </main>
    </>
  );
}
